---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Containers:
    - Portainer:
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        description: docker management
    - Dozzle:
        icon: dozzle.svg
        href: "{{HOMEPAGE_VAR_DOZZLE_URL}}"
        description: container logs
    - Homarr:
        icon: homarr.svg
        href: "{{HOMEPAGE_VAR_HOMARR_URL}}"
        description: dashboard

- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        description: media server

- Downloads:
    - qBittorrent:
        icon: qbittorrent.svg
        href: "{{HOMEPAGE_VAR_QBITTORRENT_URL}}"
        description: torrent client
    - Decypharr:
        icon: https://raw.githubusercontent.com/sirrobot01/decypharr/main/docs/src/assets/logo.png
        href: "{{HOMEPAGE_VAR_DECYPHARR_URL}}"
        description: torbox debrid

- Arr Stack:
    - Sonarr:
        icon: sonarr.svg
        href: "{{HOMEPAGE_VAR_SONARR_URL}}"
        description: tv shows
    - Radarr:
        icon: radarr.svg
        href: "{{HOMEPAGE_VAR_RADARR_URL}}"
        description: movies
    - Prowlarr:
        icon: prowlarr.svg
        href: "{{HOMEPAGE_VAR_PROWLARR_URL}}"
        description: indexer manager
    - Bazarr:
        icon: bazarr.svg
        href: "{{HOMEPAGE_VAR_BAZARR_URL}}"
        description: subtitles
