services:
  # Homepage - Application Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - socket_proxy
      - default
    ports:
      - "3000:3000"
    volumes:
      - $DOCKERDIR/appdata/homepage:/app/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      HOMEPAGE_VAR_QBITTORRENT_URL: $HOMEPAGE_VAR_QBITTORRENT_URL 
      HOMEPAGE_VAR_DOZZLE_URL: $HOMEPAGE_VAR_DOZZLE_URL  
      HOMEPAGE_VAR_BAZARR_URL: $HOMEPAGE_VAR_BAZARR_URL
      HOMEPAGE_VAR_PROWLARR_URL: $HOMEPAGE_VAR_PROWLARR_URL
      HOMEPAGE_VAR_PORTAINER_URL: $HOMEPAGE_VAR_PORTAINER_URL
      HOMEPAGE_VAR_RADARR_URL: $HOMEPAGE_VAR_RADARR_URL
      HOMEPAGE_VAR_JELLYFIN_URL: $HOMEPAGE_VAR_JELLYFIN_URL
      HOMEPAGE_VAR_SONARR_URL: $HOMEPAGE_VAR_SONARR_URL
      HOMEPAGE_VAR_HOMARR_URL: $HOMEPAGE_VAR_HOMARR_URL
      HOMEPAGE_VAR_DECYPHARR_URL: $HOMEPAGE_VAR_DECYPHARR_URL
      HOMEPAGE_VAR_JELLYFIN_API_KEY: $HOMEPAGE_VAR_JELLYFIN_API_KEY
      HOMEPAGE_VAR_SONARR_API_KEY: $HOMEPAGE_VAR_SONARR_API_KEY
      HOMEPAGE_VAR_RADARR_API_KEY: $HOMEPAGE_VAR_RADARR_API_KEY
      HOMEPAGE_VAR_PROWLARR_API_KEY: $HOMEPAGE_VAR_PROWLARR_API_KEY
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: $HOMEPAGE_VAR_QBITTORRENT_PASSWORD
      HOMEPAGE_ALLOWED_HOSTS: "$SERVER_IP:3000"